#import <ParseKit/PKSParser.h>

enum {
    HTML_TOKEN_KIND_SCRIPTTAGNAME = 14,
    HTML_TOKEN_KIND_STYLETAGNAME,
    HTML_TOKEN_KIND_DOCTYPE,
    HTML_TOKEN_KIND_LT,
    HTML_TOKEN_KIND_PROCINSTR,
    HTML_TOKEN_KIND_EQ,
    HTML_TOKEN_KIND_FWDSLASH,
    HTML_TOKEN_KIND_GT,
};

@interface HTMLParser : PKSParser

@end

