#import <PEGKit/PEGParser.h>

enum {
    EXPRESSION_TOKEN_KIND_GE = 14,
    EXPRESSION_TOKEN_KIND_COMMA,
    EXPRESSION_TOKEN_KIND_OR,
    EXPRESSION_TOKEN_KIND_LT,
    EXPRESSION_TOKEN_KIND_LE,
    EXPRESSION_TOKEN_KIND_EQ,
    EXPRESSION_TOKEN_KIND_DOT,
    EXPRESSION_TOKEN_KIND_GT,
    EXPRESSION_TOKEN_KIND_OPENPAREN,
    EXPRESSION_TOKEN_KIND_YES,
    EXPRESSION_TOKEN_KIND_NO,
    EXPRESSION_TOKEN_KIND_CLOSEPAREN,
    EXPRESSION_TOKEN_KIND_NE,
    EXPRESSION_TOKEN_KIND_AND,
};

@interface ExpressionParser : PEGParser

@end

