#import <PEGKit/PEGParser.h>

enum {
    JSON_TOKEN_KIND_FALSE = 14,
    JSON_TOKEN_KIND_CLOSECURLY,
    JSON_TOKEN_KIND_OPENBRACKET,
    JSON_TOKEN_KIND_NULLLITERAL,
    JSON_TOKEN_KIND_COMMA,
    JSON_TOKEN_KIND_TRUE,
    JSON_TOKEN_KIND_CLOSEBRACKET,
    JSON_TOKEN_KIND_OPENCURLY,
    JSON_TOKEN_KIND_COLON,
};

@interface JSONParser : PEGParser

@end

