#import <PEGKit/PEGParser.h>

enum {
    METHODS_TOKEN_KIND_INT = 14,
    METHODS_TOKEN_KIND_CLOSE_CURLY,
    METHODS_TOKEN_KIND_COMMA,
    METHODS_TOKEN_KIND_VOID,
    METHODS_TOKEN_KIND_OPEN_PAREN,
    METHODS_TOKEN_KIND_OPEN_CURLY,
    METHODS_TOKEN_KIND_CLOSE_PAREN,
    METHODS_TOKEN_KIND_SEMI_COLON,
};

@interface MethodsParser : PEGParser

@end

